# Generated by Django 6.0.7 on 2026-09-06 22:06

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("runtime", "0017_event_delivery_repair_cycle"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="workspace",
            name="applied_images",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workspace",
            name="release_target",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
